In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
#from google.colab import files
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import io


In [3]:
df=pd.read_csv('/content/sample_data/car data.csv')
df

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Selling_type Transmission  Owner  
0         Dealer       Manual      0  
1         Dealer       Manual      0  
2         Dealer       Manual      0  
3         Dealer       Manual      0  
4         Dealer       Manual      0  
..           ...          ...    ...  
296       Dealer       Manual      0  
297       Dealer       Manual      0  
298       Dealer       Manual      0  
299       Dealer       Manual      0  
300       Dealer       Manual      0  

[301 rows x 9 columns]

In [4]:
print("Total NAN values: ")
print(df.isnull().sum())
print()
print()
print("--------------------info-----------------------")
print()
df.info()

Total NAN values: 
Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64


--------------------info-----------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [5]:
#ENCODING CATEGORICAL DATA
one_hot_encoded_data=pd.get_dummies(df,columns=['Fuel_Type'])
print(one_hot_encoded_data)


    Car_Name  Year  Selling_Price  Present_Price  Driven_kms Selling_type  \
0       ritz  2014           3.35           5.59       27000       Dealer   
1        sx4  2013           4.75           9.54       43000       Dealer   
2       ciaz  2017           7.25           9.85        6900       Dealer   
3    wagon r  2011           2.85           4.15        5200       Dealer   
4      swift  2014           4.60           6.87       42450       Dealer   
..       ...   ...            ...            ...         ...          ...   
296     city  2016           9.50          11.60       33988       Dealer   
297     brio  2015           4.00           5.90       60000       Dealer   
298     city  2009           3.35          11.00       87934       Dealer   
299     city  2017          11.50          12.50        9000       Dealer   
300     brio  2016           5.30           5.90        5464       Dealer   

    Transmission  Owner  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol 

In [ ]:
#df['Fuel_Type'].replace('petrol',1.0, inplace=True)
#df['Fuel_Type'].replace('diesel',2.0, inplace=True)
#df['Fuel_Type'].replace('gas',3.0, inplace=True)
#df

In [6]:
one_hot_encoded_data=pd.get_dummies(df,columns=['Selling_type'])
print(one_hot_encoded_data)

    Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Transmission  Owner  Selling_type_Dealer  Selling_type_Individual  
0         Manual      0                

In [7]:
one_hot_encoded_data=pd.get_dummies(df,columns=['Transmission'])
print(one_hot_encoded_data)

    Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Selling_type  Owner  Transmission_Automatic  Transmission_Manual  
0         Dealer      0                 

In [8]:
#df['Selling_type'].replace('Dealer',1.0, inplace=True)
#df['Selling_type'].replace('Individual',2.0, inplace=True)
#df

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [10]:
#null values
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [22]:
x_columns=['Year','Selling_Price','Driven_kms','Owner']
y_columns=['Selling_Price']

x = df[x_columns]
y = df[y_columns]


In [23]:

x = x.to_numpy().reshape(-1, len(x_columns))
y = y.to_numpy().reshape(-1, len(y_columns))


In [24]:
#x_encoded = pd.get_dummies(x, columns=['Fuel_Type', 'Transmission'], drop_first=True)

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8)

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
print(x_train,x_test,y_train,y_test)


[[2.01100e+03 2.95000e+00 4.99980e+04 0.00000e+00]
 [2.01400e+03 6.50000e-01 2.35000e+04 0.00000e+00]
 [2.01700e+03 9.00000e-01 1.30000e+03 0.00000e+00]
 [2.01000e+03 4.50000e-01 2.70000e+04 0.00000e+00]
 [2.01300e+03 5.11000e+00 3.61980e+04 0.00000e+00]
 [2.01200e+03 1.25000e+00 5.00000e+04 0.00000e+00]
 [2.01600e+03 6.60000e+00 1.60020e+04 0.00000e+00]
 [2.01700e+03 7.90000e+00 3.43500e+03 0.00000e+00]
 [2.00800e+03 1.70000e-01 5.00000e+05 0.00000e+00]
 [2.01500e+03 2.35000e+01 4.70000e+04 0.00000e+00]
 [2.01700e+03 1.70000e+01 8.70000e+03 0.00000e+00]
 [2.01700e+03 1.65000e+00 4.00000e+03 0.00000e+00]
 [2.01600e+03 8.99000e+00 9.01000e+03 0.00000e+00]
 [2.01300e+03 2.65000e+00 6.45320e+04 0.00000e+00]
 [2.01700e+03 5.75000e+00 1.24790e+04 0.00000e+00]
 [2.01500e+03 6.00000e-01 2.90000e+04 0.00000e+00]
 [2.01000e+03 2.65000e+00 4.14420e+04 0.00000e+00]
 [2.01100e+03 1.50000e-01 3.50000e+04 1.00000e+00]
 [2.01400e+03 1.35000e+00 1.65000e+04 1.00000e+00]
 [2.01500e+03 6.50000e-01 5.000

In [27]:
x_train.shape

(240, 4)

In [28]:
y_train.shape

(240, 1)

In [29]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)


LinearRegression()

In [30]:
y_pred = lr.predict(x_test)

In [31]:
import sklearn.metrics as sm
print("Mean absolute error =", (sm.mean_absolute_error(y_test, y_pred)))
print("Mean squared error =", (sm.mean_squared_error(y_test, y_pred)))
print("R^2 score =", (sm.r2_score(y_test, y_pred)))

Mean absolute error = 7.4574021821149e-12
Mean squared error = 1.1405071568071454e-22
R^2 score = 1.0
